const lessonData = {};

lessonData["01_CobraEffect.mp3"] = [{
    text: "1. The Cobra Effect. During the time the British ruled India, there were too many venomous cobra snakes in the city of Delhi. The government wanted to make the streets safe for everyone. So, they started a special reward system. They offered good money to any local person who brought in a dead cobra. At first, this plan worked perfectly well. People killed many snakes and got their money. The number of wild cobras went down significantly. But then, some clever people had a new idea. They realized they could make a lot of money very easily. They started secret snake farms inside their own houses. They bred hundreds of cobras just to kill them and get the reward money from the British. After some time, the government found out about these secret farms. They were very angry and immediately stopped the reward system. Because there was no more money, the snake farmers did not want the cobras anymore. They opened their cages and released all the farmed snakes into the streets. In the end, the city of Delhi had more cobras than before the reward system started. Human plans completely failed.",
    dict: { "venomous": "zehirli", "reward": "ödül", "significantly": "önemli ölçüde", "secret": "gizli", "bred": "yetiştirdiler", "immediately": "hemen", "released": "serbest bıraktılar", "failed": "başarısız oldu" },
    questions: [ {q:"Did the British rule India at that time?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government start a special reward system?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people start secret snake farms?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government stop the reward system?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the snake farmers keep the cobras as pets?", a_en:"No", a_tr:"Hayır"}, {q:"Did they release the farmed snakes into the streets?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the city have more cobras in the end?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_HanoiRatBounty.mp3"] = [{
    text: "2. The Hanoi Rat Bounty. In the early 1900s, the French government controlled Vietnam. In the city of Hanoi, there was a terrible problem with rats. The rats were everywhere, especially in the dark new sewer system. The government needed a fast solution to this health crisis. They created a special bounty program. They promised to pay money to local people for every single rat they killed. To prove the rat was dead, people only needed to bring the rat's tail to the government office. Soon, thousands of tails were brought in daily. The government paid a lot of money. However, health officials started noticing something very strange. They saw living rats running around the city without tails! The local rat catchers were very smart. They caught the rats, cut off their tails for the money, and then released the live rats back into the sewers. They did this so the rats could have more babies. More babies meant more tails, and more money in the future. The French eventually discovered this trick and stopped paying. The rat population grew even larger than before. The plan to stop the rats completely failed.",
    dict: { "sewer system": "kanalizasyon sistemi", "solution": "çözüm", "bounty": "ödül/başına para", "tail": "kuyruk", "noticing": "fark etmeye", "catchers": "yakalayıcılar", "released": "serbest bıraktılar", "discovered": "keşfetti", "trick": "numara/hile" },
    questions: [ {q:"Was there a terrible problem with rats in Hanoi?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government create a bounty program?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people bring rat heads to get money?", a_en:"No", a_tr:"Hayır"}, {q:"Did people bring rat tails to get money?", a_en:"Yes", a_tr:"Evet"}, {q:"Did health officials see living rats without tails?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the local people release the rats back into the sewers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the plan to stop the rats succeed?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["03_BarrelOfRats.mp3"] = [{
    text: "3. The Barrel of Rats. There is a famous story about a very dark way to control pests. This method does not use any poison. It uses the animals against themselves. Imagine an island that is completely covered in hungry, dangerous rats. A man wants to get rid of them. He takes an empty oil barrel and puts it deep in the ground. He ties a sweet piece of coconut to the top. The rats smell the delicious food, walk onto the barrel, and fall inside. Soon, the barrel is completely full of trapped rats. The man does not kill them. He just waits quietly. The rats get extremely hungry. Because they have no food, they begin to fight. They eat each other to survive the terrible trap. After a long time, only one or two very strong rats are left alive. These surviving rats have completely changed. They are deeply traumatized. The man takes these survivors and releases them back onto the island. Now, they do not want to eat coconut or normal food anymore. They only want to hunt and eat other rats. The man turned the animal into a weapon against its own kind.",
    dict: { "pests": "haşereler", "empty": "boş", "barrel": "varil", "trapped": "tuzağa düşmüş", "survive": "hayatta kalmak", "traumatized": "travma geçirmiş", "survivors": "hayatta kalanlar", "weapon": "silah" },
    questions: [ {q:"Does this method use poison?", a_en:"No", a_tr:"Hayır"}, {q:"Does the man use an empty oil barrel?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the rats fall inside the barrel?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the man kill the trapped rats himself?", a_en:"No", a_tr:"Hayır"}, {q:"Do the rats eat each other to survive?", a_en:"Yes", a_tr:"Evet"}, {q:"Are the surviving rats deeply traumatized?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the surviving rats only want to hunt and eat other rats?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_BattleOfPelusium.mp3"] = [{
    text: "4. The Battle of Pelusium. In ancient times, the powerful Persian Empire wanted to conquer the country of Egypt. The Egyptian city of Pelusium was very strong. It had high stone walls and brave soldiers. The Persian king, Cambyses II, needed a clever trick to win. He knew something very important about the Egyptian culture. The Egyptians worshipped a goddess named Bastet. This goddess looked exactly like a cat. Because of this, cats were deeply sacred in Egypt. It was a terrible crime to hurt a cat, punishable by death. The Persian king ordered his army to paint pictures of cats on all their shields. The soldiers also carried live cats, dogs, and sheep in front of them as they marched toward the city walls. When the Egyptian archers looked down, they were terrified. They were afraid that their arrows might accidentally hit and kill a sacred animal. They believed this mistake would make their gods very angry. Because of this deep religious fear, the Egyptian soldiers refused to shoot their weapons. They did not fight back at all. The Persian army easily walked in and conquered the city using only cats.",
    dict: { "conquer": "fethetmek", "worshipped": "taptılar", "sacred": "kutsal", "punishable": "cezalandırılabilir", "shields": "kalkanlar", "archers": "okçular", "terrified": "dehşete düşmüş", "religious fear": "dini korku", "refused": "reddettiler" },
    questions: [ {q:"Did the Persian Empire want to conquer Egypt?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Egyptians worship a goddess named Bastet?", a_en:"Yes", a_tr:"Evet"}, {q:"Were cats deeply sacred in Egypt?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Persian army paint pictures of cats on their shields?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the soldiers carry live cats in front of them?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Egyptian archers shoot their arrows?", a_en:"No", a_tr:"Hayır"}, {q:"Did the Persian army conquer the city?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["05_BlackCatsPlague.mp3"] = [{
    text: "5. Black Cats and the Plague. During the Middle Ages in Europe, people were very superstitious. They strongly believed in magic, dangerous witches, and evil spirits. Unfortunately, people started to believe that cats, especially black cats, belonged to the devil. In the year 1233, the Pope wrote an official document saying black cats were truly evil. Because the people were so afraid, they started to hunt and kill cats everywhere. They destroyed thousands of cats across Europe. But this created a massive, hidden problem for everyone. Cats are the natural enemies of rats. When the cats disappeared, the rats had no predators left to hunt them. The rat population quickly grew completely out of control. There were millions of rats in the streets and homes. This became a horrible tragedy when ships arrived carrying a terrible disease called the Black Death. The disease was spread by fleas that lived on the rats. Because there were so many rats everywhere, the deadly disease spread incredibly fast. It killed millions of people across Europe. By trying to destroy an imaginary evil, the people accidentally helped a real disease destroy their world. Nature's balance was completely broken.",
    dict: { "superstitious": "batıl inançlı", "devil": "şeytan", "document": "belge", "disappeared": "ortadan kayboldu", "predators": "yırtıcılar/avcılar", "tragedy": "trajedi", "disease": "hastalık", "fleas": "pireler", "imaginary": "hayali" },
    questions: [ {q:"Were people in Europe very superstitious?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they believe black cats belonged to the devil?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people start hunting and killing cats?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the rat population grow out of control?", a_en:"Yes", a_tr:"Evet"}, {q:"Did ships arrive carrying a disease called the Black Death?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the disease spread by fleas on the rats?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the people accidentally help the disease spread?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_FourPestsCampaign.mp3"] = [{
    text: "6. The Four Pests Campaign. In the 1950s, the Chinese government started a massive new health program. They called it the Four Pests Campaign. The goal was to quickly kill four animals that spread disease or ate important crops. These animals were mosquitoes, flies, rats, and sparrows. Sparrows are small birds that love to eat grain. Millions of people worked together every day to kill the birds. They destroyed hidden nests, broke eggs, and hit loud pots with sticks to scare the birds. The birds flew in the sky until they died from total exhaustion. Soon, there were almost no sparrows left anywhere in China. The government proudly thought this was a great success. However, they made a terrible mistake. Sparrows do not just eat grain. They also eat millions of dangerous insects, especially locusts. Without the birds, the locust population grew incredibly fast. Massive, dark clouds of insects flew across the whole country. The insects ate all the farm crops and green plants. This caused a huge famine. Millions of people did not have enough food to eat. In the end, the government had to import sparrows from other countries to fix the terrible mistake.",
    dict: { "massive": "devasa/büyük", "mosquitoes": "sivrisinekler", "sparrows": "serçeler", "grain": "tahıl", "exhaustion": "tükenmişlik/yorgunluk", "locusts": "çekirgeler", "famine": "kıtlık/açlık" },
    questions: [ {q:"Did the Chinese government start the Four Pests Campaign?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they want to kill sparrows?", a_en:"Yes", a_tr:"Evet"}, {q:"Did millions of people work together to kill the birds?", a_en:"Yes", a_tr:"Evet"}, {q:"Did sparrows also eat dangerous insects?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the locust population grow very fast without the birds?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the insects eat all the farm crops?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government have to import sparrows to fix it?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["07_GreatEmuWar.mp3"] = [{
    text: "7. The Great Emu War. After World War I, many Australian soldiers became peaceful farmers. They started growing large fields of wheat in western Australia. In the year 1932, they faced a very strange, unexpected enemy. About twenty thousand emus arrived on their quiet farms. Emus are very large, fast birds that cannot fly at all. They were incredibly hungry and started eating all the valuable wheat. The farmers urgently asked the government for help. The government sent professional soldiers with heavy machine guns to fight the birds. People jokingly called this 'The Great Emu War.' The soldiers thought it would be very easy to shoot the large birds. But the emus were incredibly smart and fast. When the soldiers started shooting, the birds ran away in all different directions. They ran much faster than the military trucks could drive. Over several weeks, the soldiers used thousands of heavy bullets, but they only killed a few hundred birds. The emus completely destroyed the important crops. Finally, the frustrated military gave up and went home. The farmers lost their wheat, and the giant birds won the war. It is a funny but completely true story.",
    dict: { "peaceful": "barışçıl/huzurlu", "unexpected": "beklenmedik", "enemy": "düşman", "valuable": "değerli", "machine guns": "makineli tüfekler", "directions": "yönler", "bullets": "mermiler", "frustrated": "hayal kırıklığına uğramış/hüsrana uğramış" },
    questions: [ {q:"Did Australian soldiers become peaceful farmers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did twenty thousand emus arrive on their farms?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government send soldiers with machine guns?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the emus very slow birds?", a_en:"No", a_tr:"Hayır"}, {q:"Did the soldiers shoot thousands of bullets?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the soldiers kill all twenty thousand birds?", a_en:"No", a_tr:"Hayır"}, {q:"Did the giant birds win the war?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_OperationCatDrop.mp3"] = [{
    text: "8. Operation Cat Drop. In the 1950s, the island of Borneo had a big, dangerous problem with mosquitoes. These insects carried a deadly disease called malaria. The World Health Organization wanted to help the people. They sprayed a strong, powerful chemical everywhere to kill the mosquitoes. The plan worked, and the mosquitoes finally died. But the chemical caused a surprising chain reaction. The local lizards ate the poisoned bugs. The village cats then ate the poisoned lizards and died. Because there were no cats left, the local rat population exploded quickly. The rats brought a new, worse disease to the jungle villages. The people needed cats immediately to stop the dangerous rats. The Royal Air Force had to create a very strange, secret mission called 'Operation Cat Drop.' They collected thousands of healthy, live cats. They put the cats into special wooden boxes and attached strong parachutes to them. The airplanes flew high over the jungle villages and dropped the cats from the sky. The cats landed safely, hunted the rats, and saved the villages. It is a perfect example of how changing one small thing in nature changes everything else around it.",
    dict: { "deadly": "ölümcül", "disease": "hastalık", "chemical": "kimyasal", "chain reaction": "zincirleme reaksiyon", "poisoned": "zehirlenmiş", "exploded": "patladı (arttı)", "parachutes": "paraşütler", "safely": "güvenle" },
    questions: [ {q:"Did Borneo have a big problem with mosquitoes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the World Health Organization spray a strong chemical?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the village cats eat poisoned lizards and die?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the rat population explode quickly?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the rats bring a new disease?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Royal Air Force drop thousands of live cats from airplanes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the cats hunt the rats and save the villages?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["09_CaneToad.mp3"] = [{
    text: "9. The Cane Toad. In the 1930s, farmers in Australia had a terrible problem with their sugar cane crops. A type of beetle was eating the plants and destroying their valuable business. The farmers heard about a large, heavy toad from South America called the cane toad. They believed this incredibly hungry toad would eat the beetles and save the farms. So, they carefully brought exactly one hundred and two toads to Australia and released them. However, the hopeful plan was a complete disaster. The toads could not jump high enough to reach the beetles on the tall plants. Instead of eating beetles, the toads simply ate everything else on the ground. They multiplied extremely fast. Even worse, the cane toads are highly poisonous to other animals. When local animals like snakes, lizards, or pet dogs tried to eat the strange toads, they died almost immediately. Today, there are over two hundred million cane toads living in Australia. They are spreading across the whole country, destroying native wildlife everywhere they go. The farmers tried to fix a small bug problem and accidentally created one of the worst animal invasions in modern history.",
    dict: { "beetle": "böcek", "destroying": "mahveden", "released": "serbest bıraktılar", "disaster": "felaket", "multiplied": "çoğaldılar", "poisonous": "zehirli", "immediately": "hemen", "invasions": "istilalar" },
    questions: [ {q:"Did farmers in Australia have a problem with beetles?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they bring cane toads from South America?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the toads jump high enough to eat the beetles?", a_en:"No", a_tr:"Hayır"}, {q:"Did the toads eat everything else on the ground?", a_en:"Yes", a_tr:"Evet"}, {q:"Are cane toads highly poisonous to other animals?", a_en:"Yes", a_tr:"Evet"}, {q:"Are there over two hundred million cane toads in Australia today?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the hopeful plan a complete disaster?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_MongooseAndRat.mp3"] = [{
    text: "10. The Mongoose and the Rat. In the 1800s, busy farmers in Hawaii were growing large amounts of sugar cane. But they had a huge, expensive problem with rats. The clever rats were hiding in the fields and eating the valuable crops. The farmers urgently needed a natural predator to kill the rats. They decided to bring small, fast animals called mongooses from India. Mongooses are famous around the world for hunting rats and snakes. The farmers released them into the green fields and happily waited for the problem to be solved. But the farmers forgot one very important biological fact. Rats are nocturnal animals, which means they are awake at night and sleep during the day. Mongooses are diurnal animals, which means they are awake during the day and sleep deeply at night. The two animals almost never even met each other in the fields! Because the mongooses could not find the rats, they started hunting the beautiful native birds and slow turtles of Hawaii instead. The rat problem stayed exactly the same, and the local wildlife was destroyed. It was a very simple mistake with terrible, permanent consequences for the island.",
    dict: { "urgently": "acilen", "predator": "yırtıcı/avcı", "biological fact": "biyolojik gerçek", "nocturnal": "gececil (gece aktif)", "diurnal": "gündüzcül (gündüz aktif)", "native": "yerli", "turtles": "kaplumbağalar", "permanent consequences": "kalıcı sonuçlar" },
    questions: [ {q:"Did farmers in Hawaii have a huge problem with rats?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they bring mongooses from India to kill the rats?", a_en:"Yes", a_tr:"Evet"}, {q:"Are rats nocturnal animals?", a_en:"Yes", a_tr:"Evet"}, {q:"Are mongooses also nocturnal animals?", a_en:"No", a_tr:"Hayır"}, {q:"Did the two animals meet each other often in the fields?", a_en:"No", a_tr:"Hayır"}, {q:"Did the mongooses start hunting native birds and turtles?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the rat problem stay exactly the same?", a_en:"Yes", a_tr:"Evet"} ]
}];lessonData["11_TibblesTheCat.mp3"] = [{
    text: "11. Tibbles the Cat. In the late 1890s, a man named David Lyall got a quiet job as a lighthouse keeper. He moved to a tiny, lonely island near New Zealand called Stephens Island. Because it was so quiet there, he brought his pregnant pet cat, named Tibbles. This small island was very special to science. It was home to a tiny bird called the Stephens Island Wren. This beautiful little bird could not fly at all, and it had never seen a predator before. When Tibbles and her new kittens started carefully exploring the island, they quickly found the birds. The friendly birds did not know they needed to run away from danger. Tibbles would catch the birds and proudly bring them to David's house. David realized these birds were a brand new species, but he was far too late. Within just a few short years, Tibbles and her wild family hunted every single wren on the island. The entire species was completely wiped out. It is a sad and famous story. A single domestic cat caused the complete extinction of an entire species of bird just by following her natural hunting instincts.",
    dict: { "lighthouse keeper": "fener bekçisi", "pregnant": "hamile", "predator": "yırtıcı/avcı", "species": "tür", "wiped out": "yok edildi", "domestic": "evcil", "extinction": "neslinin tükenmesi", "instincts": "içgüdüler" },
    questions: [ {q:"Was David Lyall a lighthouse keeper?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he bring his pregnant pet cat to the island?", a_en:"Yes", a_tr:"Evet"}, {q:"Could the Stephens Island Wren fly?", a_en:"No", a_tr:"Hayır"}, {q:"Did the friendly birds run away from danger?", a_en:"No", a_tr:"Hayır"}, {q:"Did Tibbles and her kittens hunt every single wren?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the bird species survive?", a_en:"No", a_tr:"Hayır"}, {q:"Did a single domestic cat cause an extinction?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["12_VulturesAndRabies.mp3"] = [{
    text: "12. Vultures and Rabies. In India, beautiful cows are deeply respected, and many people do not eat beef. When cows get very old or sick, kind farmers give them a medicine called diclofenac to stop their pain. When the cows eventually die of old age, farmers leave the bodies outside. For thousands of years, huge birds called vultures would come and quickly eat the dead cows. They were nature's perfect garbage cleaners. But the helpful cow medicine was extremely toxic to the vultures. Millions of vultures ate the dead cows and died almost immediately. Soon, the skies were completely empty, and there were almost no vultures left in India. Because the big birds were gone, millions of dead cows stayed rotting on the ground. Feral dogs started eating the meat instead. The wild dog population exploded from millions to tens of millions very quickly. Because there were so many stray dogs constantly fighting for food, a terrible disease called rabies spread rapidly. Many people were bitten by the sick dogs. A simple medicine meant to kindly help cows accidentally caused a massive human health crisis by totally breaking the natural food chain.",
    dict: { "respected": "saygı duyulan", "toxic": "zehirli/toksik", "garbage": "çöp", "rotting": "çürüyen", "feral": "vahşi", "stray": "sokak (hayvanı)", "rabies": "kuduz", "bitten": "ısırılmış" },
    questions: [ {q:"Are cows deeply respected in India?", a_en:"Yes", a_tr:"Evet"}, {q:"Did farmers give old cows a medicine?", a_en:"Yes", a_tr:"Evet"}, {q:"Were vultures nature's perfect garbage cleaners?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the cow medicine toxic to the vultures?", a_en:"Yes", a_tr:"Evet"}, {q:"Did feral dogs eat the dead cows instead?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a disease called rabies spread rapidly?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a simple medicine cause a massive health crisis?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_PassengerPigeon.mp3"] = [{
    text: "13. The Passenger Pigeon. Two hundred years ago, the passenger pigeon was the absolute most common bird in North America. There were literally billions of them everywhere. When a huge flock of these birds flew across the sky, it would block the bright sun for hours. People honestly thought there were so many pigeons that they could never disappear. Because the birds were incredibly easy to catch and tasted very good, humans started hunting them for cheap meat. When the telegraph and railroads were invented, hunters could communicate very quickly. They followed the massive flocks of birds by fast train across the huge country. They killed millions of pigeons every single day. They selfishly cut down entire forests just to get the small baby birds from their nests. The numbers dropped very fast. But people confidently kept hunting, believing nature would easily replace them. They were completely wrong. By the year 1900, there were absolutely no wild passenger pigeons left anywhere in the world. The very last bird, named Martha, died completely alone in a zoo in 1914. Humans totally destroyed a population of billions simply because they thought the resource was infinite.",
    dict: { "common": "yaygın/sıradan", "flock": "sürü", "disappear": "ortadan kaybolmak", "communicate": "iletişim kurmak", "selfishly": "bencilce", "replace": "yerine koymak", "infinite": "sonsuz" },
    questions: [ {q:"Was the passenger pigeon the most common bird in North America?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people think they could never disappear?", a_en:"Yes", a_tr:"Evet"}, {q:"Did hunters use telegraphs and railroads to follow them?", a_en:"Yes", a_tr:"Evet"}, {q:"Did hunters kill millions of pigeons every single day?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people believe nature would easily replace the birds?", a_en:"Yes", a_tr:"Evet"}, {q:"Are there any wild passenger pigeons left today?", a_en:"No", a_tr:"Hayır"}, {q:"Did humans destroy a population of billions?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["14_EscobarHippos.mp3"] = [{
    text: "14. The Escobar Hippos. In the 1980s, a very famous criminal named Pablo Escobar lived in the country of Colombia. He had a lot of money and built a massive private zoo at his huge house. He illegally imported many wild animals from Africa, including four large, heavy hippos. When Escobar suddenly died, the government quickly took control of his property. They moved most of the zoo animals to new, safe homes. However, the hippos were far too big and aggressive to catch safely, so the government just left them in a local pond. The four hippos easily escaped into the main river system of Colombia. They absolutely loved the warm river water and had plenty of food to eat. Most importantly, they had absolutely no natural predators like lions or crocodiles to stop them. The hippos started having many babies. Today, there are over one hundred and thirty wild hippos living happily in South America. They are aggressive, dangerous to local fishermen, and their massive waste is polluting the rivers. A rich criminal's illegal pets have now become the largest invasive animal species on the entire planet, and no one knows how to safely stop them.",
    dict: { "criminal": "suçlu", "illegally": "yasadışı olarak", "imported": "ithal etti", "aggressive": "saldırgan/agresif", "predators": "yırtıcılar", "polluting": "kirleten", "invasive": "istilacı" },
    questions: [ {q:"Did Pablo Escobar build a massive private zoo?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he illegally import hippos from Africa?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government leave the hippos in a local pond?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the hippos have natural predators in Colombia?", a_en:"No", a_tr:"Hayır"}, {q:"Are there over one hundred wild hippos in South America today?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they dangerous to local fishermen?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they the largest invasive animal species on the planet?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["15_KillerBees.mp3"] = [{
    text: "15. The Killer Bees. In the year 1956, smart scientists in Brazil had a great idea. They wanted to help local farmers produce much more honey. They knew that European bees were very gentle but did not make much honey in hot weather. African bees made lots of excellent honey but were extremely aggressive. The scientists decided to breed the two types of bees together in a special laboratory. They desperately wanted to create a perfect 'super bee.' But confident human plans often fail. A careless visitor to the laboratory accidentally opened a special, locked door. Twenty-six queens of the aggressive African bees quickly escaped into the Brazilian forest. These dangerous new bees multiplied and spread incredibly fast. They traveled north completely across South America, Central America, and straight into the United States. These 'killer bees' are very dangerous. If a person or an animal gets too close to their nest, thousands of angry bees will attack at the exact same time. They will aggressively chase a running person for a very long distance. The scientists only wanted to make more honey, but they accidentally created an unstoppable, highly aggressive insect that aggressively took over two entire continents.",
    dict: { "gentle": "nazik/uysal", "laboratory": "laboratuvar", "desperately": "umutsuzca", "careless": "dikkatsiz", "chase": "kovalamak", "unstoppable": "durdurulamaz", "continents": "kıtalar" },
    questions: [ {q:"Did scientists in Brazil want to help farmers produce more honey?", a_en:"Yes", a_tr:"Evet"}, {q:"Were European bees extremely aggressive?", a_en:"No", a_tr:"Hayır"}, {q:"Did a careless visitor accidentally open a locked door?", a_en:"Yes", a_tr:"Evet"}, {q:"Did twenty-six queens of the African bees escape?", a_en:"Yes", a_tr:"Evet"}, {q:"Do killer bees attack at the exact same time?", a_en:"Yes", a_tr:"Evet"}, {q:"Will they aggressively chase a running person?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the scientists accidentally create an unstoppable insect?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["16_RabbitProofFence.mp3"] = [{
    text: "16. The Rabbit-Proof Fence. In the 1850s, a wealthy British man moved to Australia and wanted to hunt small animals for sport. He foolishly released twenty-four wild rabbits onto his beautiful land. Australia is a very warm country with lots of fresh food and absolutely no natural predators for rabbits. The twenty-four rabbits quickly turned into millions of hungry animals. The rabbits moved rapidly across the huge country, eating all the green grass and completely destroying the land. The desperate farmers needed to save their valuable farms. The Australian government decided to build a massive, thick wall. They built a strong fence that was over two thousand miles long to stop the rabbits from moving west. It was one of the absolute longest fences in the world. But the grand plan failed completely. Rabbits are genuinely excellent at digging. They simply dug deep tunnels straight under the fence and walked freely to the other side. Also, the gates in the fence were sometimes left completely open by careless travelers. The rabbits happily continued to spread everywhere. Today, there are over two hundred million rabbits in Australia. A simple hunting hobby created an environmental disaster that a massive wall could not stop.",
    dict: { "foolishly": "aptalca", "desperate": "çaresiz", "thick": "kalın", "digging": "kazma", "freely": "özgürce", "careless": "dikkatsiz", "disaster": "felaket" },
    questions: [ {q:"Did a British man foolishly release twenty-four wild rabbits in Australia?", a_en:"Yes", a_tr:"Evet"}, {q:"Are there many natural predators for rabbits in Australia?", a_en:"No", a_tr:"Hayır"}, {q:"Did the rabbits completely destroy the land?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Australian government build a massive, thick fence?", a_en:"Yes", a_tr:"Evet"}, {q:"Could the rabbits dig deep tunnels straight under the fence?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the grand plan to stop the rabbits succeed?", a_en:"No", a_tr:"Hayır"}, {q:"Are there over two hundred million rabbits in Australia today?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["17_PigWar.mp3"] = [{
    text: "17. The Pig War. In the year 1859, the United States and Great Britain were angrily arguing over a small island called San Juan. Both hardworking American farmers and British workers lived together on the beautiful island. The political situation was very tense, but absolutely no one wanted to start a bloody war. One quiet morning, an American farmer named Lyman Cutlar looked directly out his window. He saw a large, hungry black pig eating the fresh potatoes in his garden. The farmer was extremely angry and violently shot the pig. Unfortunately, the dead pig belonged to a British man. The British man aggressively demanded money. The American proudly refused to pay. The silly argument grew so big that the national military got involved. The United States quickly sent hundreds of armed soldiers with heavy cannons to the island. Great Britain sent several extremely large war ships. For several weeks, the two massive armies aggressively watched each other, totally ready to fight a deadly, terrible war over a single dead animal. Luckily, nobody shot their heavy guns. The powerful leaders finally talked and calmly solved the problem peacefully. It is remembered as the Pig War, a huge conflict caused entirely by a hungry animal.",
    dict: { "arguing": "tartışıyor", "tense": "gergin", "violently": "şiddetle", "demanded": "talep etti", "cannons": "toplar", "conflict": "çatışma", "peacefully": "barışçıl bir şekilde" },
    questions: [ {q:"Were the United States and Great Britain arguing over a small island?", a_en:"Yes", a_tr:"Evet"}, {q:"Did an American farmer shoot a hungry black pig?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the British man aggressively demand money?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the American farmer proudly pay the money?", a_en:"No", a_tr:"Hayır"}, {q:"Did the national military get involved in the argument?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the two armies fight a deadly, bloody war?", a_en:"No", a_tr:"Hayır"}, {q:"Was the problem finally solved peacefully?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["18_GhostNets.mp3"] = [{
    text: "18. Ghost Nets in the Ocean. Commercial sea fishing is a massive, global industry today. Huge ships use absolutely enormous plastic nets to catch thousands of fish at the exact same time. These nets are incredibly strong and very heavy. Sometimes, during completely terrible ocean storms or bad accidents, these huge nets violently break away from the fishing boats. They fall quickly into the deep, dark ocean. But the terrible nets do not stop working at all. They become dangerous 'ghost nets.' These mostly invisible traps float silently through the cold water for many long decades. They aggressively catch colorful fish, beautiful sea turtles, smart dolphins, and even huge whales. The trapped, frightened animals cannot breathe properly and quickly die. The heavy weight of the dead animals makes the net sink straight to the bottom of the sea. After small crabs quickly eat the dead animals, the net becomes very light again. It floats right back up to the top and happily starts catching more animals. It is a completely terrible, endless cycle of death. Humans cleverly created a strong tool to feed people, but when they lost control of it, the tool directly became an independent, silent killer in the ocean.",
    dict: { "commercial": "ticari", "enormous": "kocaman/devasa", "invisible": "görünmez", "float": "yüzmek/süzülmek", "breathe": "nefes almak", "properly": "düzgün bir şekilde", "sink": "batmak" },
    questions: [ {q:"Do huge ships use enormous plastic nets for fishing?", a_en:"Yes", a_tr:"Evet"}, {q:"Do these nets sometimes break away during terrible ocean storms?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the nets stop catching fish when they fall into the ocean?", a_en:"No", a_tr:"Hayır"}, {q:"Do they aggressively catch sea turtles, dolphins, and whales?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the heavy weight of the dead animals make the net sink?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the net float right back up after crabs eat the dead animals?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it a completely terrible, endless cycle of death?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["19_BloodBounty.mp3"] = [{
    text: "19. The Blood Bounty. Many years ago, a totally unique animal lived on a green island near Australia. It was called the amazing Tasmanian Tiger. It looked exactly like a wild dog but with beautiful tiger stripes on its back. When wealthy European farmers excitedly moved to the island, they brought thousands of valuable sheep. Sometimes, the soft sheep would suddenly die or completely disappear. The angry farmers quickly blamed the Tasmanian Tiger, even though wild, feral dogs were usually the real killers. The government strongly wanted to strictly protect the farmers' money. They immediately started a cruel blood bounty. They boldly promised to pay a large amount of cash to absolutely anyone who brought them a dead Tasmanian Tiger. Greedy hunters quickly went deep into the dark forests. They aggressively killed thousands of these beautiful, innocent animals just to easily get the reward money. They selfishly killed so many that the government eventually had to stop the program. But it was far too late. The entire population was destroyed. The very last known Tasmanian Tiger died completely alone in a zoo in 1936. By trying to blindly protect a few farm animals, the government cruelly paid people to completely erase a unique animal forever.",
    dict: { "unique": "eşsiz/benzersiz", "stripes": "çizgiler", "blamed": "suçladılar", "strictly": "kesinlikle/sıkıca", "cruel": "zalim", "greedy": "açgözlü", "innocent": "masum" },
    questions: [ {q:"Did the Tasmanian Tiger look like a wild dog with tiger stripes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did angry farmers blame the Tasmanian Tiger for killing their sheep?", a_en:"Yes", a_tr:"Evet"}, {q:"Were wild, feral dogs usually the real killers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government start a cruel blood bounty?", a_en:"Yes", a_tr:"Evet"}, {q:"Did greedy hunters aggressively kill thousands of these innocent animals?", a_en:"Yes", a_tr:"Evet"}, {q:"Are there any Tasmanian Tigers alive in the wild today?", a_en:"No", a_tr:"Hayır"}, {q:"Was the entire population destroyed?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_GoatAndGalapagos.mp3"] = [{
    text: "20. The Goat and the Galapagos. The gorgeous Galapagos Islands are incredibly famous for their amazing nature. Huge, slow giant tortoises live happily there and eat the special, unique plants. Many years ago, rough sailors and dangerous pirates frequently visited the quiet islands. They casually left a few wild goats there so they would easily have fresh meat when they returned. Goats are incredibly tough, strong animals. They can eat absolutely almost anything and easily survive without much fresh water. The few abandoned goats quickly multiplied into hundreds of thousands. The very hungry goats ate absolutely all the green plants, bushes, and trees on the islands. They completely destroyed the entire natural environment. The beautiful, slow giant tortoises had absolutely no food left. They tragically started to slowly starve to death. The hungry goats were simply too fast for the tortoises to fairly compete with. The worried government had to take very extreme action to save the famous tortoises. They used loud helicopters and highly trained hunters to carefully remove absolutely every single goat from the islands. It took many long years and a lot of money to completely fix the massive damage. Leaving a few goats almost destroyed one of the most important natural habitats ever.",
    dict: { "gorgeous": "muhteşem", "tortoises": "kara kaplumbağaları", "pirates": "korsanlar", "abandoned": "terk edilmiş", "tragically": "trajik bir şekilde", "starve": "açlıktan ölmek", "extreme": "aşırı" },
    questions: [ {q:"Are the Galapagos Islands famous for giant tortoises?", a_en:"Yes", a_tr:"Evet"}, {q:"Did rough sailors and pirates leave wild goats there?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the abandoned goats multiply into hundreds of thousands?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the hungry goats eat absolutely all the green plants?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the giant tortoises slowly starve to death?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government use helicopters and hunters to remove the goats?", a_en:"Yes", a_tr:"Evet"}, {q:"Did it take a lot of money to fix the massive damage?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["21_AsianCarp.mp3"] = [{
    text: "21. The Asian Carp. In the 1970s, hard-working fish farmers in the United States had a terrible problem with dirty water. Their extremely large ponds were completely full of thick green algae and ugly weeds. To easily clean the water naturally, they quickly imported a special, hungry fish called the Asian Carp. These amazing fish eat huge amounts of green plants and clean the dirty water very quickly. The smart plan worked completely perfectly at first. But during a very heavy, violent rainstorm, the huge ponds completely flooded. The fast water washed the heavy carp directly into the huge Mississippi River. This was an absolutely massive, terrible disaster. Asian Carp grow incredibly large and aggressively eat twenty percent of their heavy body weight every single day. They quickly multiplied rapidly and eagerly traveled far up the long river. They aggressively ate all the fresh food that native fish desperately needed to easily survive. Also, when fast boats confidently drive past them, the loud, sudden noise completely scares the nervous fish. The heavy, frightened fish literally jump high into the bright air and dangerously hit people, frequently breaking noses and arms. Now, the government is desperately spending millions trying to build strong electronic walls to stop these terrible fish.",
    dict: { "dirty": "kirli", "algae": "yosun", "imported": "ithal ettiler", "flooded": "su bastı/taştı", "eagerly": "hevesle", "desperately": "çaresizce", "frightened": "korkmuş" },
    questions: [ {q:"Did fish farmers in the US have a problem with dirty water?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they import Asian Carp to easily clean the water naturally?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a violent rainstorm flood the huge ponds?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fast water wash the heavy carp into the Mississippi River?", a_en:"Yes", a_tr:"Evet"}, {q:"Do Asian Carp aggressively eat the food that native fish desperately need?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the frightened fish literally jump high into the air?", a_en:"Yes", a_tr:"Evet"}, {q:"Do they sometimes dangerously hit people in fast boats?", a_en:"Yes", a_tr:"Evet"} ]
}];
