const lessonData = {};

lessonData["01_CobraEffect.mp3"] = [{
    text: "1. The Cobra Effect. During the time the British ruled India, there were too many venomous cobra snakes in the city of Delhi. The government wanted to make the streets safe for everyone. So, they started a special reward system. They offered good money to any local person who brought in a dead cobra. At first, this plan worked perfectly well. People killed many snakes and got their money. The number of wild cobras went down significantly. But then, some clever people had a new idea. They realized they could make a lot of money very easily. They started secret snake farms inside their own houses. They bred hundreds of cobras just to kill them and get the reward money from the British. After some time, the government found out about these secret farms. They were very angry and immediately stopped the reward system. Because there was no more money, the snake farmers did not want the cobras anymore. They opened their cages and released all the farmed snakes into the streets. In the end, the city of Delhi had more cobras than before the reward system started. Human plans completely failed.",
    dict: { "venomous": "zehirli", "reward": "ödül", "significantly": "önemli ölçüde", "secret": "gizli", "bred": "yetiştirdiler", "immediately": "hemen", "released": "serbest bıraktılar", "failed": "başarısız oldu" },
    questions: [ {q:"Did the British rule India at that time?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government start a special reward system?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people start secret snake farms?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government stop the reward system?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the snake farmers keep the cobras as pets?", a_en:"No", a_tr:"Hayır"}, {q:"Did they release the farmed snakes into the streets?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the city have more cobras in the end?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_HanoiRatBounty.mp3"] = [{
    text: "2. The Hanoi Rat Bounty. In the early 1900s, the French government controlled Vietnam. In the city of Hanoi, there was a terrible problem with rats. The rats were everywhere, especially in the dark new sewer system. The government needed a fast solution to this health crisis. They created a special bounty program. They promised to pay money to local people for every single rat they killed. To prove the rat was dead, people only needed to bring the rat's tail to the government office. Soon, thousands of tails were brought in daily. The government paid a lot of money. However, health officials started noticing something very strange. They saw living rats running around the city without tails! The local rat catchers were very smart. They caught the rats, cut off their tails for the money, and then released the live rats back into the sewers. They did this so the rats could have more babies. More babies meant more tails, and more money in the future. The French eventually discovered this trick and stopped paying. The rat population grew even larger than before. The plan to stop the rats completely failed.",
    dict: { "sewer system": "kanalizasyon sistemi", "solution": "çözüm", "bounty": "ödül/başına para", "tail": "kuyruk", "noticing": "fark etmeye", "catchers": "yakalayıcılar", "released": "serbest bıraktılar", "discovered": "keşfetti", "trick": "numara/hile" },
    questions: [ {q:"Was there a terrible problem with rats in Hanoi?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government create a bounty program?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people bring rat heads to get money?", a_en:"No", a_tr:"Hayır"}, {q:"Did people bring rat tails to get money?", a_en:"Yes", a_tr:"Evet"}, {q:"Did health officials see living rats without tails?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the local people release the rats back into the sewers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the plan to stop the rats succeed?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["03_BarrelOfRats.mp3"] = [{
    text: "3. The Barrel of Rats. There is a famous story about a very dark way to control pests. This method does not use any poison. It uses the animals against themselves. Imagine an island that is completely covered in hungry, dangerous rats. A man wants to get rid of them. He takes an empty oil barrel and puts it deep in the ground. He ties a sweet piece of coconut to the top. The rats smell the delicious food, walk onto the barrel, and fall inside. Soon, the barrel is completely full of trapped rats. The man does not kill them. He just waits quietly. The rats get extremely hungry. Because they have no food, they begin to fight. They eat each other to survive the terrible trap. After a long time, only one or two very strong rats are left alive. These surviving rats have completely changed. They are deeply traumatized. The man takes these survivors and releases them back onto the island. Now, they do not want to eat coconut or normal food anymore. They only want to hunt and eat other rats. The man turned the animal into a weapon against its own kind.",
    dict: { "pests": "haşereler", "empty": "boş", "barrel": "varil", "trapped": "tuzağa düşmüş", "survive": "hayatta kalmak", "traumatized": "travma geçirmiş", "survivors": "hayatta kalanlar", "weapon": "silah" },
    questions: [ {q:"Does this method use poison?", a_en:"No", a_tr:"Hayır"}, {q:"Does the man use an empty oil barrel?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the rats fall inside the barrel?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the man kill the trapped rats himself?", a_en:"No", a_tr:"Hayır"}, {q:"Do the rats eat each other to survive?", a_en:"Yes", a_tr:"Evet"}, {q:"Are the surviving rats deeply traumatized?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the surviving rats only want to hunt and eat other rats?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_BattleOfPelusium.mp3"] = [{
    text: "4. The Battle of Pelusium. In ancient times, the powerful Persian Empire wanted to conquer the country of Egypt. The Egyptian city of Pelusium was very strong. It had high stone walls and brave soldiers. The Persian king, Cambyses II, needed a clever trick to win. He knew something very important about the Egyptian culture. The Egyptians worshipped a goddess named Bastet. This goddess looked exactly like a cat. Because of this, cats were deeply sacred in Egypt. It was a terrible crime to hurt a cat, punishable by death. The Persian king ordered his army to paint pictures of cats on all their shields. The soldiers also carried live cats, dogs, and sheep in front of them as they marched toward the city walls. When the Egyptian archers looked down, they were terrified. They were afraid that their arrows might accidentally hit and kill a sacred animal. They believed this mistake would make their gods very angry. Because of this deep religious fear, the Egyptian soldiers refused to shoot their weapons. They did not fight back at all. The Persian army easily walked in and conquered the city using only cats.",
    dict: { "conquer": "fethetmek", "worshipped": "taptılar", "sacred": "kutsal", "punishable": "cezalandırılabilir", "shields": "kalkanlar", "archers": "okçular", "terrified": "dehşete düşmüş", "religious fear": "dini korku", "refused": "reddettiler" },
    questions: [ {q:"Did the Persian Empire want to conquer Egypt?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Egyptians worship a goddess named Bastet?", a_en:"Yes", a_tr:"Evet"}, {q:"Were cats deeply sacred in Egypt?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Persian army paint pictures of cats on their shields?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the soldiers carry live cats in front of them?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Egyptian archers shoot their arrows?", a_en:"No", a_tr:"Hayır"}, {q:"Did the Persian army conquer the city?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["05_BlackCatsPlague.mp3"] = [{
    text: "5. Black Cats and the Plague. During the Middle Ages in Europe, people were very superstitious. They strongly believed in magic, dangerous witches, and evil spirits. Unfortunately, people started to believe that cats, especially black cats, belonged to the devil. In the year 1233, the Pope wrote an official document saying black cats were truly evil. Because the people were so afraid, they started to hunt and kill cats everywhere. They destroyed thousands of cats across Europe. But this created a massive, hidden problem for everyone. Cats are the natural enemies of rats. When the cats disappeared, the rats had no predators left to hunt them. The rat population quickly grew completely out of control. There were millions of rats in the streets and homes. This became a horrible tragedy when ships arrived carrying a terrible disease called the Black Death. The disease was spread by fleas that lived on the rats. Because there were so many rats everywhere, the deadly disease spread incredibly fast. It killed millions of people across Europe. By trying to destroy an imaginary evil, the people accidentally helped a real disease destroy their world. Nature's balance was completely broken.",
    dict: { "superstitious": "batıl inançlı", "devil": "şeytan", "document": "belge", "disappeared": "ortadan kayboldu", "predators": "yırtıcılar/avcılar", "tragedy": "trajedi", "disease": "hastalık", "fleas": "pireler", "imaginary": "hayali" },
    questions: [ {q:"Were people in Europe very superstitious?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they believe black cats belonged to the devil?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people start hunting and killing cats?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the rat population grow out of control?", a_en:"Yes", a_tr:"Evet"}, {q:"Did ships arrive carrying a disease called the Black Death?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the disease spread by fleas on the rats?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the people accidentally help the disease spread?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_FourPestsCampaign.mp3"] = [{
    text: "6. The Four Pests Campaign. In the 1950s, the Chinese government started a massive new health program. They called it the Four Pests Campaign. The goal was to quickly kill four animals that spread disease or ate important crops. These animals were mosquitoes, flies, rats, and sparrows. Sparrows are small birds that love to eat grain. Millions of people worked together every day to kill the birds. They destroyed hidden nests, broke eggs, and hit loud pots with sticks to scare the birds. The birds flew in the sky until they died from total exhaustion. Soon, there were almost no sparrows left anywhere in China. The government proudly thought this was a great success. However, they made a terrible mistake. Sparrows do not just eat grain. They also eat millions of dangerous insects, especially locusts. Without the birds, the locust population grew incredibly fast. Massive, dark clouds of insects flew across the whole country. The insects ate all the farm crops and green plants. This caused a huge famine. Millions of people did not have enough food to eat. In the end, the government had to import sparrows from other countries to fix the terrible mistake.",
    dict: { "massive": "devasa/büyük", "mosquitoes": "sivrisinekler", "sparrows": "serçeler", "grain": "tahıl", "exhaustion": "tükenmişlik/yorgunluk", "locusts": "çekirgeler", "famine": "kıtlık/açlık" },
    questions: [ {q:"Did the Chinese government start the Four Pests Campaign?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they want to kill sparrows?", a_en:"Yes", a_tr:"Evet"}, {q:"Did millions of people work together to kill the birds?", a_en:"Yes", a_tr:"Evet"}, {q:"Did sparrows also eat dangerous insects?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the locust population grow very fast without the birds?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the insects eat all the farm crops?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government have to import sparrows to fix it?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["07_GreatEmuWar.mp3"] = [{
    text: "7. The Great Emu War. After World War I, many Australian soldiers became peaceful farmers. They started growing large fields of wheat in western Australia. In the year 1932, they faced a very strange, unexpected enemy. About twenty thousand emus arrived on their quiet farms. Emus are very large, fast birds that cannot fly at all. They were incredibly hungry and started eating all the valuable wheat. The farmers urgently asked the government for help. The government sent professional soldiers with heavy machine guns to fight the birds. People jokingly called this 'The Great Emu War.' The soldiers thought it would be very easy to shoot the large birds. But the emus were incredibly smart and fast. When the soldiers started shooting, the birds ran away in all different directions. They ran much faster than the military trucks could drive. Over several weeks, the soldiers used thousands of heavy bullets, but they only killed a few hundred birds. The emus completely destroyed the important crops. Finally, the frustrated military gave up and went home. The farmers lost their wheat, and the giant birds won the war. It is a funny but completely true story.",
    dict: { "peaceful": "barışçıl/huzurlu", "unexpected": "beklenmedik", "enemy": "düşman", "valuable": "değerli", "machine guns": "makineli tüfekler", "directions": "yönler", "bullets": "mermiler", "frustrated": "hayal kırıklığına uğramış/hüsrana uğramış" },
    questions: [ {q:"Did Australian soldiers become peaceful farmers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did twenty thousand emus arrive on their farms?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government send soldiers with machine guns?", a_en:"Yes", a_tr:"Evet"}, {q:"Were the emus very slow birds?", a_en:"No", a_tr:"Hayır"}, {q:"Did the soldiers shoot thousands of bullets?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the soldiers kill all twenty thousand birds?", a_en:"No", a_tr:"Hayır"}, {q:"Did the giant birds win the war?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_OperationCatDrop.mp3"] = [{
    text: "8. Operation Cat Drop. In the 1950s, the island of Borneo had a big, dangerous problem with mosquitoes. These insects carried a deadly disease called malaria. The World Health Organization wanted to help the people. They sprayed a strong, powerful chemical everywhere to kill the mosquitoes. The plan worked, and the mosquitoes finally died. But the chemical caused a surprising chain reaction. The local lizards ate the poisoned bugs. The village cats then ate the poisoned lizards and died. Because there were no cats left, the local rat population exploded quickly. The rats brought a new, worse disease to the jungle villages. The people needed cats immediately to stop the dangerous rats. The Royal Air Force had to create a very strange, secret mission called 'Operation Cat Drop.' They collected thousands of healthy, live cats. They put the cats into special wooden boxes and attached strong parachutes to them. The airplanes flew high over the jungle villages and dropped the cats from the sky. The cats landed safely, hunted the rats, and saved the villages. It is a perfect example of how changing one small thing in nature changes everything else around it.",
    dict: { "deadly": "ölümcül", "disease": "hastalık", "chemical": "kimyasal", "chain reaction": "zincirleme reaksiyon", "poisoned": "zehirlenmiş", "exploded": "patladı (arttı)", "parachutes": "paraşütler", "safely": "güvenle" },
    questions: [ {q:"Did Borneo have a big problem with mosquitoes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the World Health Organization spray a strong chemical?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the village cats eat poisoned lizards and die?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the rat population explode quickly?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the rats bring a new disease?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Royal Air Force drop thousands of live cats from airplanes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the cats hunt the rats and save the villages?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["09_CaneToad.mp3"] = [{
    text: "9. The Cane Toad. In the 1930s, farmers in Australia had a terrible problem with their sugar cane crops. A type of beetle was eating the plants and destroying their valuable business. The farmers heard about a large, heavy toad from South America called the cane toad. They believed this incredibly hungry toad would eat the beetles and save the farms. So, they carefully brought exactly one hundred and two toads to Australia and released them. However, the hopeful plan was a complete disaster. The toads could not jump high enough to reach the beetles on the tall plants. Instead of eating beetles, the toads simply ate everything else on the ground. They multiplied extremely fast. Even worse, the cane toads are highly poisonous to other animals. When local animals like snakes, lizards, or pet dogs tried to eat the strange toads, they died almost immediately. Today, there are over two hundred million cane toads living in Australia. They are spreading across the whole country, destroying native wildlife everywhere they go. The farmers tried to fix a small bug problem and accidentally created one of the worst animal invasions in modern history.",
    dict: { "beetle": "böcek", "destroying": "mahveden", "released": "serbest bıraktılar", "disaster": "felaket", "multiplied": "çoğaldılar", "poisonous": "zehirli", "immediately": "hemen", "invasions": "istilalar" },
    questions: [ {q:"Did farmers in Australia have a problem with beetles?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they bring cane toads from South America?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the toads jump high enough to eat the beetles?", a_en:"No", a_tr:"Hayır"}, {q:"Did the toads eat everything else on the ground?", a_en:"Yes", a_tr:"Evet"}, {q:"Are cane toads highly poisonous to other animals?", a_en:"Yes", a_tr:"Evet"}, {q:"Are there over two hundred million cane toads in Australia today?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the hopeful plan a complete disaster?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_MongooseAndRat.mp3"] = [{
    text: "10. The Mongoose and the Rat. In the 1800s, busy farmers in Hawaii were growing large amounts of sugar cane. But they had a huge, expensive problem with rats. The clever rats were hiding in the fields and eating the valuable crops. The farmers urgently needed a natural predator to kill the rats. They decided to bring small, fast animals called mongooses from India. Mongooses are famous around the world for hunting rats and snakes. The farmers released them into the green fields and happily waited for the problem to be solved. But the farmers forgot one very important biological fact. Rats are nocturnal animals, which means they are awake at night and sleep during the day. Mongooses are diurnal animals, which means they are awake during the day and sleep deeply at night. The two animals almost never even met each other in the fields! Because the mongooses could not find the rats, they started hunting the beautiful native birds and slow turtles of Hawaii instead. The rat problem stayed exactly the same, and the local wildlife was destroyed. It was a very simple mistake with terrible, permanent consequences for the island.",
    dict: { "urgently": "acilen", "predator": "yırtıcı/avcı", "biological fact": "biyolojik gerçek", "nocturnal": "gececil (gece aktif)", "diurnal": "gündüzcül (gündüz aktif)", "native": "yerli", "turtles": "kaplumbağalar", "permanent consequences": "kalıcı sonuçlar" },
    questions: [ {q:"Did farmers in Hawaii have a huge problem with rats?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they bring mongooses from India to kill the rats?", a_en:"Yes", a_tr:"Evet"}, {q:"Are rats nocturnal animals?", a_en:"Yes", a_tr:"Evet"}, {q:"Are mongooses also nocturnal animals?", a_en:"No", a_tr:"Hayır"}, {q:"Did the two animals meet each other often in the fields?", a_en:"No", a_tr:"Hayır"}, {q:"Did the mongooses start hunting native birds and turtles?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the rat problem stay exactly the same?", a_en:"Yes", a_tr:"Evet"} ]
}];
